# Application Configuration
spring.application.name=Gateway-Service
server.port = 8080

eureka.client.service-url.defaultzone = http://localhost:8761/eureka/

# Mantenimiento
spring.cloud.gateway.routes[0].id=mantenimiento-service
spring.cloud.gateway.routes[0].uri=lb://TALLER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/taller/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

# Repuesto
spring.cloud.gateway.routes[1].id=repuesto-service
spring.cloud.gateway.routes[1].uri=lb://REPUESTO-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/repuesto/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# Facturacion
spring.cloud.gateway.routes[2].id=facturacion-service
spring.cloud.gateway.routes[2].uri=lb://FACTURACION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/factura/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# Identity
spring.cloud.gateway.routes[3].id=identity-service
spring.cloud.gateway.routes[3].uri=lb://IDENTITY-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**

# Cliente
spring.cloud.gateway.routes[4].id=cliente-service
spring.cloud.gateway.routes[4].uri=lb://CLIENTE-SERVICE
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/cliente/**
spring.cloud.gateway.routes[4].filters[0]=AuthenticationFilter

#Proveedor
spring.cloud.gateway.routes[5].id=proveedor-service
spring.cloud.gateway.routes[5].uri=lb://PROVEEDOR-SERVICE
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/proveedor/**
spring.cloud.gateway.routes[5].filters[0]=AuthenticationFilter

