# Application Configuration
spring.application.name=Gateway-Service
server.port = 8080

eureka.client.service-url.defaultzone = http://localhost:8761/eureka/

# Taller
spring.cloud.gateway.routes[0].id=taller-service
spring.cloud.gateway.routes[0].uri=lb://Taller-Service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/taller/**
spring.cloud.gateway.routes[0].filters[0]=AuthenticationFilter

# Repuesto
spring.cloud.gateway.routes[1].id=repuesto-service
spring.cloud.gateway.routes[1].uri=lb://Repuesto-Service
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/repuesto/**
spring.cloud.gateway.routes[1].filters[0]=AuthenticationFilter

# Facturacion
spring.cloud.gateway.routes[2].id=facturacion-service
spring.cloud.gateway.routes[2].uri=lb://Facturacion-Service
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/factura/**
spring.cloud.gateway.routes[2].filters[0]=AuthenticationFilter

# Identity
spring.cloud.gateway.routes[3].id=identity-service
spring.cloud.gateway.routes[3].uri=lb://Identity-Service
spring.cloud.gateway.routes[3].predicates[0]=Path=/auth/**
